### ISSUE TITLE
"Debug" Mode

### ISSUE THREAD

**Issue by apoyatos** [imagicbell/ublockly#11]
Hi, looking through the code we were wondering if there was a way of "debugging" the blocks( i.e stopping the execution and going block by block), and if it's not implemented we would like to know if it's possible and in that case what would we have to do. Thanks for your time.

**Comment by imagicbell** [comment]
Good point 👍  
Currently it is not implemented. However, there might be a way to do it. 
The general idea is:
_Based on the graph structure of blocks, we can traverse all the blocks by `block.next` and put them in a sequence. Then run blocks in the sequence one by one._
Please reference my current `run` logic in [CSharpInterpreter.CS](https://github.com/imagicbell/ublockly/blob/master/Source/Script/CodeDB/CSharp/CSharpInterpreter.cs).
```C#
IEnumerator RunWorkspace(Workspace workspace) {...}
IEnumerator RunBlock(Block block) {...}
```
Also attention the loop `break`, `continue` issue, which can stop the loop block.
```C#
if (ControlCmdtor.SkipRunByControlFlow(block))
 {
    yield break;
 }
```
PULL REQUEST IS WELCOME~

**Comment by imagicbell** [comment]
Hello there,
The debug mode you mentioned is on now. Please check the latest update. Thanks for your advice 😄
