### ISSUE TITLE
Getting a error on trying to ignore some block categories

### ISSUE THREAD

**Issue by toamig** [imagicbell/ublockly#12]
Hello there.
I'm trying to read only some block categories depending on the integrated sensors from our program. I'm trying to continue the loop if the sensor readed is not integrated. Although, it keeps giving me this `ArgumentNullException: value cannot be null Parameter name: collection` error. Could you give me some help trying to understand what can possibly be going on? Thanks in advance!

Trying to ignore some resParams from the m_BlockJsonFiles in BlockResMgr.cs

![Imgur](https://i.imgur.com/5pPZ5cA.png)

**Comment by toamig** [comment]
I found out I could stop category initialization from the ToolBoxConfig.cs file 

![Imgur](https://i.imgur.com/e2f6Oew.png)

Now my problem is that the category does not initialize, but category names are still displayable and clickabl on the UI

![Imgur](https://i.imgur.com/6KVjfMM.png)

**Comment by imagicbell** [comment]
![image](https://user-images.githubusercontent.com/2181062/113654502-927a9780-96ca-11eb-9210-08f8e67f3920.png)
![image](https://user-images.githubusercontent.com/2181062/113654588-bb029180-96ca-11eb-9ef8-2e2ab9509c85.png)

Did you remove the the category from the toolbox config file? Please see the **Toolbox** doc from [here](https://github.com/imagicbell/ublockly/#blockressettings). 
If you change this config file, then you don't need to modify code, as this config file indicates what categories to show in side toolbox.

**Comment by toamig** [comment]
But am I supposed to change the jsonfile while the program is running? 
Beause I want the categories to be dynamic depending on the integration or not of some sensors

thanks for the response!

**Comment by toamig** [comment]
I was able to fix this, by deleting elements from the List of categories before initing them. Thanks for the help
