### ISSUE TITLE
After resetting the workspace, the code keeps running without any blocks 

### ISSUE THREAD

**Issue by toamig** [imagicbell/ublockly#13]
When I switch scenes and reset the workspace and create a new one, this green ligh stays there and the code keeps running even without any blocks. Am I supposed to do anything else to prevent this from happening?

![Imgur](https://i.imgur.com/NjB10sU.png)

**Comment by imagicbell** [comment]
Sorry for the mess of disposing workspace. Lacking test :)
Please check this [new commit](https://github.com/imagicbell/ublockly/commit/ccf4f65de8118e9feadd8a26081dafdf7a94a6cc).

**Comment by toamig** [comment]
No problem at all, bugs happen quite a lot, it's perfectly understandable!
Thank you so much for ur constant support and for letting us use your work!

Just another doubt to be clarified, what is the propper way of resetting the workspace now with the new code?

I'm handling events from the WorkspaceView for when I'm transitioning in and out of Ublockly's interface. What methods should I assign to each event?

**Comment by imagicbell** [comment]
Just the same as I said last time. I also add it [here](https://github.com/imagicbell/ublockly#how-to-reset-workspace) with a little bit new code modifications.
1. If you need to switch scenes, which means WorkspaceView will be destroyed and re-created, you can follow the Brutal way.
2. If you don't want to destroy the WorkspaceView object, you can just follow the second method: Reset block views and toolbox respectively.

**Comment by toamig** [comment]
Btw do you have any idea why these tests are failing? 
I don't think we changed anything related to this. Were they passing on your project?
![Imgur](https://i.imgur.com/RnZlYKu.png)

**Comment by imagicbell** [comment]
Yes, mine is passed. 
![image](https://user-images.githubusercontent.com/2181062/114657435-a3f31d80-9d22-11eb-959f-5c5caf9ed787.png)
There must be some log to get a hint?

**Comment by toamig** [comment]
I'm getting this for some reason 
![Imgur](https://i.imgur.com/4vEpvg7.png)

![Imgur](https://i.imgur.com/9pB0C9M.png)

**Comment by imagicbell** [comment]
Sorry that I couldn't figure out what is wrong.
Could you please check if you have changed `class FieldAngle` or `class Number`. Or you could debug into the code to check what is going wrong.
