### ISSUE TITLE
Snap fails in some blocks

### ISSUE THREAD

**Issue by apoyatos** [imagicbell/ublockly#19]
Hi while developing our project we've encountered an issue with the snapping in long blocks. It seems that the connections positions doesn't update when we add code blocks. For example in the for block if we had 5 instructions, to add a new block at the bottom of the for we have to drag the block not to the bottom of the for block but to the middle of it. 
I've attached a video showing what i mean in case it's not clear. Is there a way to fix this or a way to improve the snapping.? Thanks

https://user-images.githubusercontent.com/37510165/119393321-10255180-bcd1-11eb-929e-405e424a5421.mp4

**Comment by imagicbell** [comment]
Did you update the project to the newest. I have fixed this problem in this [commit](https://github.com/imagicbell/ublockly/commit/fb9eb7cfd63f750ead6b7421968de93835180573)





https://user-images.githubusercontent.com/2181062/119596436-b8daca80-be11-11eb-9169-03b37b789345.mov

**Comment by apoyatos** [comment]
Oh, we were using an outdated version. It works now, thanks.
