### ISSUE TITLE
Detail link is fail

### ISSUE THREAD

**Issue by vml933** [imagicbell/ublockly#20]
These link is 404, would you fix it, thanks!
http://imagicbell.github.io/unity/2017/10/11/blockly-one.html
http://imagicbell.github.io/unity/2017/10/14/blockly-two.html
http://imagicbell.github.io/unity/2017/10/22/blockly-three.html
http://imagicbell.github.io/unity/2017/10/31/blockly-four.html

**Comment by imagicbell** [comment]
Fixed.
Sorry for that. I have just updated my blog site and forgot to update README.

**Comment by vml933** [comment]
Thanks very much.
