### ISSUE TITLE
Procedures blocks problem

### ISSUE THREAD

**Issue by vml933** [imagicbell/ublockly#24]
Hello, I have 3 question.
1. When I rename block: procedure  name  on canvas , the block doesn't  update block label at the first time, rename block again the label will update the name which I updated at first time, not the second one, is it a bug?

2. When I drag a block:procedure on canvas and add some statement in block and run,  everything work is fine. but  save xml, then  load xml, the block: procedure can't work property, is it a bug?

3.  When I drag a block:procedure to canvas, then drag the latest block which auto created from toolbox to canvas, click the left top gear icon, it show "Exception: Can't find dialog prefab for procedures_callnoreturn_mutator, Please ensure you configure it in "BlockResSettings", I can add  "procedures_callnoreturn_mutator" in BlockResSettings, but I can't found any prefab or script like "ProcedureCallMutatorDialog", is it a unfinished part?

Thanks for help.

**Comment by imagicbell** [comment]
Sorry for the bugs. Please see the newly commits:
758dd8d5ec4cfad3dd19e4b54f20f2ee18dd3489
cf4c9dcc74feaabf9d434e4f0888c3a8327adb8b
Hopefully, they are fixed.

One more thing, please rebuild the block prefabs again. The procedure caller prefab was attached with a "settings" image, but now it is removed. Only the procedure definition prefab is allowed to have the "settings".

**Comment by vml933** [comment]
procedure work fine, very appreciate for quick fixed.

**Comment by vml933** [comment]
Hello, 
one more question, if a procedure block with 1 row block inside, it work perfect; but more than 1 row block inside,
it throw " Language CSharp does not know how to interprete code for block type procedures_defreturn",
is it a bug?

Thanks.

**Comment by vml933** [comment]
Hi, is any update can fix above problem? 
Thanks.

**Comment by imagicbell** [comment]
Please check the update 94ef264cd08a09385460fd7ab894916318489da2
Sorry for the late fix. I am just back from my 1-week long holiday.

**Comment by vml933** [comment]
Thanks for the quick fix, very appreciate!
