### ISSUE TITLE
Can't run the example project

### ISSUE THREAD

**Issue by alu0101049151** [imagicbell/ublockly#28]
Hi,

I have  forked and cloned this repo a few hours ago and when I tried to run "Example" directory in Unity, I can't do anything. It only has an empty scene with a "Main Camera" and a "Directional Light" in the Hierarchy. Also in the Assets I have "UBlockly" and "UblocklyData" but I can't execute them either.

So I would be so grateful if you can help me or tell me if I'm doing anything wrong.

Thanks

**Comment by HerrAugust** [comment]
I think you need to copy-paste the content of the folders "UBlockly" and "UBlocklyData" inside the folder "Assets". Find attached my working project - and use at your risk.

https://owncloud.retis.santannapisa.it/index.php/s/Pz2NYXLfXA7agsE

**Comment by imagicbell** [comment]
Thanks very much. This problem happens on Windows. I think it might be because of the difference in alias path on Mac and Windows. Check this https://github.com/imagicbell/ublockly/issues/5#issuecomment-780442764

**Comment by alu0101049151** [comment]
Thank you! Definitely this was the problem. 
Solved!
