### ISSUE TITLE
Can't drag any block when build the project

### ISSUE THREAD

**Issue by alu0101049151** [imagicbell/ublockly#30]
Hi,

I've been keeping working with UBlockly and I have found the problem that, when I build the project, I can´t drag and drop any block in the Canvas. I tried to build the same project for windows and WebGL and It doesn't work in any of them. However, I don't know why, because when I run it directly form the Unity editor, works fine. 

I would be so grateful If someone can tell me what is happens or help me In some way.

Thanks in advance.

**Comment by imagicbell** [comment]
Sorry for the bug. Please update to the commit f346ec9bd948abadb9b5b78f0e6a470bc9ff3f60. Just a quick fix.

**Comment by alu0101049151** [comment]
Hi, thank you very much for the quick reply. Now it works fine in Windows, but it still does not work in WebGL since I have run it in firefox locally and it still does not work as you can see below:
![DragAndDropNotWorking](https://user-images.githubusercontent.com/56077151/127750638-925c5fd7-4669-465f-a000-aac8b4210cf7.gif)

Thanks in advance.

**Comment by imagicbell** [comment]
Please update to the newest commit cc0ff2437b2af7eb83d087e02a303d7e19b7575c. Hopefully it is fixed now.

**Comment by alu0101049151** [comment]
Now forks fine!! Thank you very much for the fix and the quick reply!
