### ISSUE TITLE
ClassToolBox: BlockView OnDrag problem?

### ISSUE THREAD

**Issue by vml933** [imagicbell/ublockly#31]
Hi:
I use theme: ClassToolBox,  after apply cc0ff24 & f346ec9, the blockView drag function not working properly,
is it a bug?

**Comment by imagicbell** [comment]
Sorry. I have a quick fix for this. But the sub-toolbox won't hide automatically now. I'll figure out a better way in the future.

**Comment by imagicbell** [comment]
Sorry. I have a quick fix for this. But the sub-toolbox won't hide automatically now if you don't mind.  I will figure out a better way in the future.

**Comment by vml933** [comment]
Thanks for the quick fix.

**Comment by imagicbell** [comment]
Hi, I have a fixed commit 226a5649bca97fee6d40dc98c6601219abed3065 now. The sub-toolbox can hide automatically now, as google blockly. Sorry for the inconvenience.

**Comment by vml933** [comment]
Thanks for the fix, ClassicToolbox now works perfect.
