### ISSUE TITLE
Next statement without a previous statement

### ISSUE THREAD

**Issue by anmartan** [imagicbell/ublockly#40]
Recently, I've been trying to implement a "start" block, so that the interpreter only reads the code that's hanging from this block. However, I found myself unable to do it: whether it is a mistake of mine, or a bug, I don't know although I believe it is the later.

When trying to write the .json file that describes the block structure, I noticed that I can add a "previousStatement" to a block, which adds a link to the block, so that it can be connected to others, or even a "previousStatement" and a "nextStatement", as in the pictures below:

![image](https://user-images.githubusercontent.com/48750779/141015635-a952a28e-34e9-4367-8b1b-03e46fd8604f.png)
![image](https://user-images.githubusercontent.com/48750779/141015667-a08f89bc-7960-4c18-81f4-1a23f2c5094a.png)

![image](https://user-images.githubusercontent.com/48750779/141015747-4c5fbeec-c8f6-4f01-a58a-21389f226b1c.png)
![image](https://user-images.githubusercontent.com/48750779/141015759-7ff01869-0502-47e3-8e90-4365e009d371.png)

Yet, when I try to add only a "nextStatement" (which is what the Start block should have), the result isn't the expected:

![image](https://user-images.githubusercontent.com/48750779/141015916-90899b8b-54e2-4676-9395-ac84f60b58a2.png)
![image](https://user-images.githubusercontent.com/48750779/141015997-755bb0d4-4350-43fa-a7bc-795734733288.png)

**Comment by imagicbell** [comment]
This commit 49c99a8d9d489b506ea352d22bde6ce25e798487 might fix your problem.
