### ISSUE TITLE
Is there a context menu function?

### ISSUE THREAD

**Issue by zxllo12** [imagicbell/ublockly#42]
Hello, thanks for open this great project!! but It's sad that there's no undo function. Or maybe I couldn't find it.
If you right-click block on Blockly, you'll find a context menu. And you can use several functions. Like "Duplicate", "Add Comment" etc. UBlockly doesn't have this function?  (I saw the explanation "context menu" in "en.json")

**Comment by imagicbell** [comment]
Yes, the feature is not provided. Please notice that this project is not 100% from Google Blockly.

**Comment by zxllo12** [comment]
I see. Thank you for your response!
