### ISSUE TITLE
The user can create infinite loops

### ISSUE THREAD

**Issue by apoyatos** [imagicbell/ublockly#6]
The player can add blocks to the workspace to create infinite loops that crash the app. Code blocks like while true or an infinite recursive function are permited. Maybe as a fix the app could put a max number of iterations so if it passes that number it stops executing the code.

**Comment by imagicbell** [comment]
Please check the hot fix. I add a max loop number, currently `Int16.MaxValue`. There will be a dialog showing up reminding of the infinite loop. Also the subsequent process will be terminated.
Thanks a lot for this issue.
