### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by toamig** [imagicbell/ublockly#8]
I've created a new i18n file with my language and added a new list item to BlockResSettings. Although, nothing changes when I run the game.

**Comment by imagicbell** [comment]
Sorry for the inconvenience. There is one more thing:
On the Line 34 in `/Assets/UBlockly/Script/Core/Blockly.cs`, change the parameter in the call 
`BlockResMgr.Get().LoadI18n(I18n.EN);`
to the value you set for `Index Name` in BlockResSettings.

This is not automatic, I know. I'll fix it in the future.
