### ISSUE TITLE
What is the colour/tooltip/helpurl paremeters in the json block configuration files used for?

### ISSUE THREAD

**Issue by LockDownPT** [imagicbell/ublockly#9]
Hi there, We are trying to use the ublockly library and we are having some doubts about the usage of some of the parameters used in the JSON block definition. 
The 3 parameters we have in doubt are the colour/helpUrl/tooltip parameters.,
We supposed the colour was used to change the colour of the block but when we tried to change it nothing happened.
The fields helpurl, tooltip we have no idea what they are used for. 

Any help would be appreciated, thanks. 😃

**Comment by imagicbell** [comment]
Thanks for choosing ublockly library.
The 3 parameters are not used anymore, but I didn’t move them away. Sorry for that 😊
There is another way to change the color of the blocks.  Please see my updated README:
[BlockResSettings](https://github.com/imagicbell/ublockly#blockressettings)
The color of blocks can be changed in toolbox files.
